name: Fluxo de teste e build

on:
  push:
    branches:
      - main
  release:
    types: [ published ]

jobs:
  tests-instituicao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Running project
        run: npm run start &

      - name: Run Cypress chrome
        run: npx cypress run --browser chrome --spec "cypress/e2e/teste-instituicao.cy.js"

      - name: Run Cypress firefox
        run: npx cypress run --browser firefox --spec "cypress/e2e/teste-instituicao.cy.js"

      - name: Run Cypress edge
        run: npx cypress run --browser edge --spec "cypress/e2e/teste-instituicao.cy.js"

  tests-usuario:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Running project
        run: npm run start &

      - name: Run Cypress chrome
        run: npx cypress run --browser chrome --spec "cypress/e2e/teste-usuario.cy.js"

      - name: Run Cypress firefox
        run: npx cypress run --browser firefox --spec "cypress/e2e/teste-usuario.cy.js"

      - name: Run Cypress edge
        run: npx cypress run --browser edge --spec "cypress/e2e/teste-usuario.cy.js"
      
      - name: Docker build
        run: docker build -t doasanguepoa-front .
      
      - name: Docker tag
        run: docker tag doasanguepoa-front ${{ secrets.DOCKER_USERNAME }}/doasanguepoa-front:latest
  
  build_and_push_to_registry:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs:
      - tests-instituicao
      - tests-usuario

    steps:
      runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: docker build -t doasanguepoa-front .
      
      - name: Docker tag
        run: docker tag doasanguepoa-front ${{ secrets.DOCKER_USERNAME }}/doasanguepoa-front:latest

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/doasanguepoa-front:latest

      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/doasanguepoa-front:latest


  push_to_registry_tag:
    if: github.event_name == 'release' && github.event.action == 'published'
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs:
      - tests-instituicao
      - tests-usuario

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/doasanguepoa-front

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
