name: Frontend

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout postagens
        uses: actions/checkout@v4.1.1
        with:
          repository: leonardogoandete/postagens
          path: postagens

#      - name: Checkout Talk
#        uses: actions/checkout@v4.1.1
#        with:
#          repository: orion-services/talk
#          path: talk

      - name: Run Postagens
        run: |
          cd postagens
          ./mvnw compile quarkus:dev &
          cd ..

#      - name: Run Talk
#        run: |
#          cd talk
#          ./mvnw compile quarkus:dev &
#          cd ..
#      - name: Run Talk frontend
#        run: |
#          cd talk/front
#          npm install
#          npm run dev &
#          cd ../..
      - name: wait for services to start
        run: |
          sleep 20

      - name: Echo running Post api
        run: curl 0.0.0.0:8081/q/metrics

#      - name: Run Cypress
#        run: |
#          cd talk/front
#          npm install
#          npm run test
#          cd ../..


