name: Frontend

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout postagens
        uses: actions/checkout@v4.1.1
        with:
          repository: leonardogoandete/postagens
          path: postagens

      - name: Checkout postagens
        uses: actions/checkout@v4.1.1
        with:
          repository: leonardogoandete/doasanguepoa-java
          path: doasanguepoa-java

      - name: Run doasanguepoa-java
        run: |
          cd doasanguepoa-java
          ./mvnw compile quarkus:dev &
          cd ..

#      - name: Run Talk frontend
#        run: |
#          cd talk/front
#          npm install
#          npm run dev &
#          cd ../..
      - name: wait for services to start
        run: |
          sleep 20

      - name: Echo running Post api
        run: |
          docker run -d leogoandete/doasanguepoa-front:v1.2.0 

      - name: Telnet
        run: |
          curl http://localhost:3000

#      - name: Run Cypress
#        run: |
#          cd talk/front
#          npm install
#          npm run test
#          cd ../..


