name: Frontend

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Variaveis de ambiente
        run: |
          export REACT_APP_URL_API_POSTAGENS=http://localhost:8081
          export REACT_APP_URL_API_LOGIN=http://localhost:8082
          echo $REACT_APP_URL_API_POSTAGENS
          echo $REACT_APP_URL_API_LOGIN
      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout postagens
        uses: actions/checkout@v4.1.1
        with:
          repository: leonardogoandete/postagens
          path: postagens

      - name: Run postagens
        run: |
          cd postagens
          ./mvnw compile quarkus:dev &
          cd ..

      - name: Checkout login
        uses: actions/checkout@v4.1.1
        with:
          repository: leonardogoandete/doasanguepoa-java
          path: doasanguepoa-java

      - name: Run login
        run: |
          cd doasanguepoa-java
          ./mvnw compile quarkus:dev &
          cd ..

      - name: Checkout front
        uses: actions/checkout@v4.1.1
        with:
          repository: leonardogoandete/doasanguepoa
          path: doasanguepoa

      - name: Run doasanguepoa front
        run: |
          cd doasanguepoa
          ls -la
          npm install
          npm run start &
          cd ..

      - name: wait for services to start
        run: |
          sleep 20

      - name: Run Cypress
        run: |
          cd doasanguepoa
          npx cypress run